# note: freq count in epochs, set 0 to ignore

task: "fit"

fit:
  wd: 0.1
  lr: 0.00001
  lr_schd: "warmup_cosine"

  epochs: 10
  optim: "adamw"
  loss_fn: "CrossEntropyLoss"
  val_freq: 0

  ckpt_freq: 10

  sp:
    warm_up_epochs: 0
    min_lr_ratio: 0.1            
    freeze_backbone: False

test:
  # normal_test will gather dict {top1 top5 pred target}
  # otherwise chibooks will only gather and save model output
  normal_test: True

inference:
  

env:
  gpus: 1
  seed: 42
  num_workers: 4
  log_root: ./test_logs

# only ImageFolder and csv_list are available
dataset:

  name: 
  root: 
  cls_idx_remap: false

  img_size: [224,224]
  
  train_batch_size: 128
  val_batch_size: 128
  test_batch_size: 128

model:
  name: 
  arch: 
  backbone_weight: 

  sp:
    # 
    freeze_backbone: True
    head_lr_scaler: 1.0